name: 'ecommerce_warehouse'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_warehouse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_warehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  ecommerce_warehouse:
    +quote_columns: false
